# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/OrderLabel.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_order_label_container(object):
    def setupUi(self, order_label_container):
        order_label_container.setObjectName("order_label_container")
        order_label_container.resize(329, 29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(order_label_container.sizePolicy().hasHeightForWidth())
        order_label_container.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(order_label_container)
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(order_label_container)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.description = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setObjectName("description")
        self.horizontalLayout_2.addWidget(self.description)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(order_label_container)
        QtCore.QMetaObject.connectSlotsByName(order_label_container)

    def retranslateUi(self, order_label_container):
        _translate = QtCore.QCoreApplication.translate
        order_label_container.setWindowTitle(_translate("order_label_container", "Form"))
        self.description.setText(_translate("order_label_container", "N X Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    order_label_container = QtWidgets.QWidget()
    ui = Ui_order_label_container()
    ui.setupUi(order_label_container)
    order_label_container.show()
    sys.exit(app.exec_())
